[config]

[templates.hyprlock]
input_path='~/.config/matugen/hyprlock.conf'
output_path='~/.config/hypr/hyprlock.conf'

[templates.gtk3]
input_path = '~/.config/matugen/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path = '~/.config/matugen/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'